name: Publish web demo

on:
  push:
    branches:
      - 'main'
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup NPM
        uses: actions/setup-node@v1
      
      - name: Build NPM package
        run: |
          cd www/
          npm run build

      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.1
        with:
          source-directory: www/dist
          target-branch: gh-pages
